repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.27.1
  hooks:
  - id: markdownlint
- repo: https://github.com/trussworks/pre-commit-hooks
  rev: v1.0.0
  hooks:
    - id: mdspell
    - id: spelling-sort

-   repo: local
    hooks:
    -   id: colrev-hooks-update
        name: "CoLRev ReviewManager: update"
        entry: colrev-hooks-update
        language: python
        stages: [commit]
        files: 'records.bib|paper.md'