title: digital-work lab
description: The digital-work lab handbook
theme: just-the-docs

url: https://digital-work-lab.github.io/handbook

footer_content:
  Edit on GitHub: <a href="{{ site.gh_edit_repository }}/edit/master/docs/{{ page.path }}">{{ site.edit_link_text }}</a>
