title: digital-work lab
description: The digital-work lab handbook
theme: just-the-docs

url: https://digital-work-lab.github.io/handbook

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
