title: digital-work lab
description: The digital-work lab handbook
theme: just-the-docs

url: https://digital-work-lab.github.io/handbook

aux_links:
  Edit on GitHub: https://github.com/digital-work-lab/handbook
