title: digital-work lab
description: The digital-work lab handbook
theme: just-the-docs

url: https://digital-work-lab.github.io/handbook

gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/digital-work-lab/handbook'
gh_edit_branch: 'main'
gh_edit_source: docs
gh_edit_view_mode: 'tree'
